### ISSUE TITLE
Error: Call to undefined function updateSubscriptionId()

### ISSUE THREAD

**Issue by fastcast4u** [FasterPay/module-whmcs#1]
/modules/gateways/callback/fasterpay.php:104 Stack trace: #0 /modules/gateways/callback/fasterpay.php(51): FasterPay_Pingback->processDeliverable(19274, Array) #1 /modules/gateways/callback/fasterpay.php(229): FasterPay_Pingback->run() #2 {main} {"exception":"[object] (Error(code: 0): Call to undefined function updateSubscriptionId() at /modules/gateways/callback/fasterpay.php:104)"} []"

**Comment by prashantbd** [comment]
This issue was resolved with our latest update.
